@servername =  http://localhost:8082

### Test Ping
GET {{servername}}/ping HTTP/1.1

### Test create setting
POST {{servername}}/app/km001/setting HTTP/1.1
Content-Type: application/json

{
 	"settingid" 	: "companyname4"
}

### Test create setting
POST {{servername}}/app/kw001/setting HTTP/1.1
Content-Type: application/json

{
 	"settingid" 	: "contactperson"
}

### Test create setting
POST {{servername}}/app/km001/setting HTTP/1.1
Content-Type: application/json

{
 	"settingid" : "address",
    "value"     : "jln abc"
}

### Test update setting
PUT {{servername}}/app/km001/setting/companyname HTTP/1.1
Content-Type: application/json

{
    "value"         : "PT ABC",
    "description"   : "Company Name"
}

### Test delete setting
DELETE {{servername}}/app/km001/setting/compayname HTTP/1.1

### Test Get setting
GET {{servername}}/app/km001/setting/companyname HTTP/1.1

### Test Get List setting
GET {{servername}}/app/km001/setting HTTP/1.1
